system:
  name: jsonwizard
  port: 9379
  db-type: mysql
  oss-type: local
  use-multipoint: false
  use-redis: false
  iplimit-count: 15000
  iplimit-time: 3600
  encrypt-key: "jsonwizard@lsy88"

mysql:
  path: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: jsonwizard
  username: root
  password: "716523"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: error
  log-zap: false

mongodb:
  username: admin
  password: ""
  path: 127.0.0.1
  port: "27017"
  database: jsonwizard
  log-zap: false

redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""

zap:
  level: info
  prefix: '[github.com/lsy88/jsonwizard]'
  format: console
  director: log
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  max-age: 0
  show-line: true
  log-in-console: true

local:
  path: uploads/file
  store-path: uploads/file

captcha:
  key-long: 6
  img-width: 240
  img-height: 80

jwt:
  signing-key: 'jsonwizard'
  expires-time: 7d
  buffer-time: 1d
  Issuer: "jsonwizard"